
# Resource: https://dev.to/s_abderemane/manual-trigger-with-github-actions-279e
on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '* * 1 * *' # once a day
  
  # Manual runs on stars
  watch:
    types: [started]


    
name: pull-latest-tweets

jobs:
  build:
    runs-on: macOS-latest
    
    if: github.actor == github.event.repository.owner.login # Only when I star
    
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install package dependencies
        run: |-
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_github('gadenbuie/tweetrmd')"
          Rscript -e "remotes::install_github('rstudio/webshot2')"
          Rscript -e "install.packages('rtweet')"
      - name: Run script
        env:
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        run: |-
          Rscript -e "source('script.R')"
      - name: Commit results
        run: |
          git commit -m "Update the latest tweet" -a || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
